#ifndef __FLOG_XCONFIG_H__
#define __FLOG_XCONFIG_H__

#define FLOG_SEVERITY_LIST \
    FLOG_SEVERITY_LIST_ITEM(DEBUG) \
    FLOG_SEVERITY_LIST_ITEM(INFO) \
    FLOG_SEVERITY_LIST_ITEM(ERROR) \

#define FLOG_MODULE_LIST \
    FLOG_MODULE_LIST_ITEM( AB, DEBUG, INFO ) \
    FLOG_MODULE_LIST_ITEM( CDEF, DEBUG, INFO ) \
    FLOG_MODULE_LIST_ITEM( GHI, INFO, INFO ) \
    FLOG_MODULE_LIST_ITEM( LOG, INFO, INFO ) \

#define FLOG_FORMAT_LIST(FA, SEVERITY, MODULE) \
    FLOG_FORMAT_LIST_ITEM(SEVMOD, ON, "%s", #SEVERITY "[" #MODULE "] ", "", FA) \
    FLOG_FORMAT_LIST_ITEM(FILE, CON, "%s", flog_file_name_shorten(__FILE__), "", FA) \
    FLOG_FORMAT_LIST_ITEM(LINE, CON, "%s", LINETOSTRING(__LINE__), "", FA) \
    FLOG_FORMAT_LIST_ITEM(FUNCTION, COFF, "%s", __FUNCTION__, "", FA) \
    FLOG_FORMAT_LIST_ITEM(PAREN, COFF, "%s", "() ", "", FA) \

#define FLOGX
#include "flogx.h"

#endif  /* __FLOG_XCONFIG_H__ */

